apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
 name: podinfo
 namespace: default
spec:
  interval: 10m
  targetNamespace: default
  prune: true
  timeout: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: "./clusters/staging/my-manifest"



